version: '3.8'

networks:
  wp_network:
    driver: bridge

volumes:
  mysl_data:
  wordpress:

services:
  db:
    image: mariadb:10.6.17-focal
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - mysl_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp_network

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3-fpm
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8001:80"
    networks:
      - wp_network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./wp-content:/var/www/html/wp-content
    networks:
      - wp_network
